Repository hana-harmoney/backend, pull requests merged in 2025-09, with the labels that each got.

#79 [FIX] 아이디 중복 시 true 반환
  src/main/java/com/example/hanaharmonybackend/service/serviceImpl/AuthServiceImpl.java
  src/main/java/com/example/hanaharmonybackend/web/controller/AuthController.java
Labels: 🐛 FIX

#83 [FEAT] 회원가입시 위,경도 추가
  src/main/java/com/example/hanaharmonybackend/domain/User.java
  src/main/java/com/example/hanaharmonybackend/service/serviceImpl/AuthServiceImpl.java
  src/main/java/com/example/hanaharmonybackend/web/dto/SignupRequest.java
Labels: 🌟 FEAT

#85 [FEAT] 거리 기반 게시글 필터링 구현
  src/main/java/com/example/hanaharmonybackend/payload/code/ErrorStatus.java
  src/main/java/com/example/hanaharmonybackend/repository/BoardRepository.java
  src/main/java/com/example/hanaharmonybackend/service/BoardService.java
  src/main/java/com/example/hanaharmonybackend/service/serviceImpl/BoardServiceImpl.java
  src/main/java/com/example/hanaharmonybackend/web/controller/BoardController.java
  src/main/java/com/example/hanaharmonybackend/web/dto/BoardNearbyDto.java
Labels: 🌟 FEAT

#91 [FEAT] 송금시 금액 포맷 설정
  src/main/java/com/example/hanaharmonybackend/service/serviceImpl/ChatMessageServiceImpl.java
Labels: 🐛 FIX

#96 [FEAT] 회원가입시 수입, 지출 내역 생성 트리거
  src/main/java/com/example/hanaharmonybackend/domain/Expense.java
  src/main/java/com/example/hanaharmonybackend/domain/Income.java
  src/main/java/com/example/hanaharmonybackend/repository/ExpenseRepository.java
  src/main/java/com/example/hanaharmonybackend/repository/IncomeRepository.java
  src/main/java/com/example/hanaharmonybackend/service/serviceImpl/AuthServiceImpl.java
Labels: 🌟 FEAT

#100 [FEAT] 통계 리포트 관련 API 구현
  src/main/java/com/example/hanaharmonybackend/domain/Report.java
  src/main/java/com/example/hanaharmonybackend/repository/ReportRepository.java
  src/main/java/com/example/hanaharmonybackend/service/ChatRoomService.java
  src/main/java/com/example/hanaharmonybackend/service/ReportService.java
  src/main/java/com/example/hanaharmonybackend/service/serviceImpl/AuthServiceImpl.java
  src/main/java/com/example/hanaharmonybackend/service/serviceImpl/ChatMessageServiceImpl.java
  src/main/java/com/example/hanaharmonybackend/service/serviceImpl/ChatRoomServiceImpl.java
  src/main/java/com/example/hanaharmonybackend/service/serviceImpl/ReportServiceImpl.java
  src/main/java/com/example/hanaharmonybackend/web/controller/ReportController.java
  src/main/java/com/example/hanaharmonybackend/web/dto/report/ReportDetailResponse.java
  src/main/java/com/example/hanaharmonybackend/web/dto/report/ReportListResponse.java
Labels: 🌟 FEAT, 🛠️ REFACTOR

#118 [FIX] principal 인증 방식 수정
  src/main/java/com/example/hanaharmonybackend/util/JwtTokenProvider.java
Labels: 🐛 FIX

#120 [FEAT] 거리 기반, 종료된 게시글 필터링 테스트 코드
  build.gradle
  src/main/java/com/example/hanaharmonybackend/repository/BoardRepository.java
  src/main/resources/application.yml
  src/test/java/com/example/hanaharmonybackend/config/TestJpaAuditingConfig.java
  src/test/java/com/example/hanaharmonybackend/repository/BoardRepositoryDistanceStatusTest.java
  src/test/java/com/example/hanaharmonybackend/service/serviceImpl/BoardNearbyServiceTest.java
Labels: 🌟 FEAT, 🛠️ REFACTOR
