Repository hana-harmoney/backend, pull requests merged in 2025-08, with the labels that each got.

#3 [FEAT] 공통 응답값 설정, RDS 연동
  src/main/java/com/example/hanaharmonybackend/domain/BaseEntity.java
  src/main/java/com/example/hanaharmonybackend/domain/enumerate/GENDER.java
  src/main/java/com/example/hanaharmonybackend/payload/ApiResponse.java
  src/main/java/com/example/hanaharmonybackend/payload/code/BaseStatus.java
  src/main/java/com/example/hanaharmonybackend/payload/code/ErrorStatus.java
  src/main/java/com/example/hanaharmonybackend/payload/code/ReasonDto.java
  src/main/java/com/example/hanaharmonybackend/payload/code/SuccessStatus.java
  src/main/java/com/example/hanaharmonybackend/payload/excpetion/CustomException.java
  src/main/java/com/example/hanaharmonybackend/payload/excpetion/GlobalExceptionHandler.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: 🌟 FEAT, 🗂️ CHORE

#11 [FEAT] 프로필 등록, 조회 api 구현
  build.gradle
  src/main/java/com/example/hanaharmonybackend/config/JwtAuthFilter.java
  src/main/java/com/example/hanaharmonybackend/config/SecurityConfig.java
  src/main/java/com/example/hanaharmonybackend/domain/DescImage.java
  src/main/java/com/example/hanaharmonybackend/domain/Profile.java
  src/main/java/com/example/hanaharmonybackend/repository/DescImageRepository.java
  src/main/java/com/example/hanaharmonybackend/repository/ProfileRepository.java
  src/main/java/com/example/hanaharmonybackend/service/FileStorageService.java
  src/main/java/com/example/hanaharmonybackend/service/ProfileService.java
  src/main/java/com/example/hanaharmonybackend/service/serviceImpl/ProfileServiceImpl.java
  src/main/java/com/example/hanaharmonybackend/service/serviceImpl/S3FileStorageServiceImpl.java
  src/main/java/com/example/hanaharmonybackend/web/controller/ProfileController.java
  src/main/java/com/example/hanaharmonybackend/web/dto/ProfileCreateRequest.java
  src/main/java/com/example/hanaharmonybackend/web/dto/ProfileResponse.java
  src/main/resources/application.yml
Labels: 🌟 FEAT

#14 [FEAT] 게시글
  src/main/java/com/example/hanaharmonybackend/config/JwtAuthFilter.java
  src/main/java/com/example/hanaharmonybackend/config/SecurityConfig.java
  src/main/java/com/example/hanaharmonybackend/domain/Board.java
  src/main/java/com/example/hanaharmonybackend/domain/Category.java
  src/main/java/com/example/hanaharmonybackend/domain/User.java
  src/main/java/com/example/hanaharmonybackend/payload/code/ErrorStatus.java
  src/main/java/com/example/hanaharmonybackend/repository/BoardRepository.java
  src/main/java/com/example/hanaharmonybackend/repository/CategoryRepository.java
  src/main/java/com/example/hanaharmonybackend/service/BoardService.java
  src/main/java/com/example/hanaharmonybackend/service/serviceImpl/BoardServiceImpl.java
  src/main/java/com/example/hanaharmonybackend/web/controller/BoardController.java
  src/main/java/com/example/hanaharmonybackend/web/dto/BoardCreateRequest.java
  src/main/java/com/example/hanaharmonybackend/web/dto/BoardResponse.java
Labels: 🌟 FEAT

#15 [FEAT] 계좌 생성로직, 조회API 구현
  .husky/commit-msg
  src/main/java/com/example/hanaharmonybackend/domain/Account.java
  src/main/java/com/example/hanaharmonybackend/domain/Pocket.java
  src/main/java/com/example/hanaharmonybackend/domain/User.java
  src/main/java/com/example/hanaharmonybackend/payload/code/ErrorStatus.java
  src/main/java/com/example/hanaharmonybackend/repository/AccountRepository.java
  src/main/java/com/example/hanaharmonybackend/service/AccountCommandService.java
  src/main/java/com/example/hanaharmonybackend/service/AccountService.java
  src/main/java/com/example/hanaharmonybackend/service/serviceImpl/AccountCommandServiceImpl.java
  src/main/java/com/example/hanaharmonybackend/service/serviceImpl/AccountServiceImpl.java
  src/main/java/com/example/hanaharmonybackend/service/serviceImpl/AuthServiceImpl.java
  src/main/java/com/example/hanaharmonybackend/util/AccountNumberGenerator.java
  src/main/java/com/example/hanaharmonybackend/web/controller/AccountController.java
  src/main/java/com/example/hanaharmonybackend/web/dto/account/AccountResponse.java
Labels: 🌟 FEAT

#20 [FIX] 게시글 이미지 s3 변환 로직 추가
  src/main/java/com/example/hanaharmonybackend/service/serviceImpl/BoardServiceImpl.java
  src/main/java/com/example/hanaharmonybackend/web/controller/BoardController.java
  src/main/java/com/example/hanaharmonybackend/web/dto/BoardCreateRequest.java
Labels: 🐛 FIX

#21 [FEAT] 로그인시 프로필 여부 반환 기능 구현
  src/main/java/com/example/hanaharmonybackend/domain/User.java
  src/main/java/com/example/hanaharmonybackend/service/AuthService.java
  src/main/java/com/example/hanaharmonybackend/service/serviceImpl/AuthServiceImpl.java
  src/main/java/com/example/hanaharmonybackend/web/controller/AuthController.java
  src/main/java/com/example/hanaharmonybackend/web/dto/LoginResponse.java
Labels: 🌟 FEAT

#22 [FEAT] 주머니 생성, 삭제 API 구현
  src/main/java/com/example/hanaharmonybackend/domain/TransactionHistory.java
  src/main/java/com/example/hanaharmonybackend/payload/code/ErrorStatus.java
  src/main/java/com/example/hanaharmonybackend/repository/PocketRepository.java
  src/main/java/com/example/hanaharmonybackend/repository/TransactionHistoryRepository.java
  src/main/java/com/example/hanaharmonybackend/service/PocketCommandService.java
  src/main/java/com/example/hanaharmonybackend/service/serviceImpl/PocketCommandServiceImpl.java
  src/main/java/com/example/hanaharmonybackend/web/controller/PocketController.java
  src/main/java/com/example/hanaharmonybackend/web/dto/pocket/PocketCreateRequest.java
  src/main/java/com/example/hanaharmonybackend/web/dto/pocket/PocketCreateResponse.java
Labels: 🌟 FEAT

#39 [FIX] 채팅방 API 수정
  src/main/java/com/example/hanaharmonybackend/config/handler/CustomHandshakeHandler.java
  src/main/java/com/example/hanaharmonybackend/service/serviceImpl/ChatRoomServiceImpl.java
Labels: 🐛 FIX

#43 [FEAT] 채팅방에서 송금 API 구현
  src/main/java/com/example/hanaharmonybackend/domain/Board.java
  src/main/java/com/example/hanaharmonybackend/domain/ChatRoom.java
  src/main/java/com/example/hanaharmonybackend/domain/Profile.java
  src/main/java/com/example/hanaharmonybackend/payload/code/ErrorStatus.java
  src/main/java/com/example/hanaharmonybackend/service/ChatMessageService.java
  src/main/java/com/example/hanaharmonybackend/service/serviceImpl/ChatMessageServiceImpl.java
  src/main/java/com/example/hanaharmonybackend/web/controller/ChatController.java
  src/main/java/com/example/hanaharmonybackend/web/dto/chatMessage/ChatMessageTransferResponse.java
Labels: 🌟 FEAT

#44 [FIX] 채팅방 송금여부 응답값 추가
  src/main/java/com/example/hanaharmonybackend/service/serviceImpl/ChatRoomServiceImpl.java
  src/main/java/com/example/hanaharmonybackend/web/dto/chatRoom/ChatRoomDetailResponse.java
Labels: 🐛 FIX

#51 [FEAT] 채팅방 단건 조회 시 상대방 이름 추가
  src/main/java/com/example/hanaharmonybackend/service/serviceImpl/ChatRoomServiceImpl.java
  src/main/java/com/example/hanaharmonybackend/web/dto/chatRoom/ChatRoomDetailResponse.java
Labels: 🌟 FEAT

#54 [REFACTOR] Service, Controller 코드 리팩토링
  src/main/java/com/example/hanaharmonybackend/repository/AccountRepository.java
  src/main/java/com/example/hanaharmonybackend/repository/BoardRepository.java
  src/main/java/com/example/hanaharmonybackend/service/serviceImpl/AccountCommandServiceImpl.java
  src/main/java/com/example/hanaharmonybackend/service/serviceImpl/AccountServiceImpl.java
  src/main/java/com/example/hanaharmonybackend/service/serviceImpl/AuthServiceImpl.java
  src/main/java/com/example/hanaharmonybackend/service/serviceImpl/BoardServiceImpl.java
  src/main/java/com/example/hanaharmonybackend/service/serviceImpl/ChatMessageServiceImpl.java
  src/main/java/com/example/hanaharmonybackend/service/serviceImpl/ChatRoomServiceImpl.java
  src/main/java/com/example/hanaharmonybackend/service/serviceImpl/PocketCommandServiceImpl.java
  src/main/java/com/example/hanaharmonybackend/service/serviceImpl/ProfileServiceImpl.java
  src/main/java/com/example/hanaharmonybackend/web/controller/AccountController.java
  src/main/java/com/example/hanaharmonybackend/web/controller/AuthController.java
  src/main/java/com/example/hanaharmonybackend/web/controller/BoardController.java
  src/main/java/com/example/hanaharmonybackend/web/controller/ProfileController.java
Labels: 🐛 FIX, 🛠️ REFACTOR

#55 [REFACTOR] 글 등록시 이미지 등록 선택으로 변경
  src/main/java/com/example/hanaharmonybackend/service/serviceImpl/BoardServiceImpl.java
  src/main/java/com/example/hanaharmonybackend/web/controller/BoardController.java
  src/main/java/com/example/hanaharmonybackend/web/dto/BoardCreateRequest.java
Labels: 🛠️ REFACTOR

#62 [FEAT] 상대방 프로필 조회
  src/main/java/com/example/hanaharmonybackend/service/ProfileService.java
  src/main/java/com/example/hanaharmonybackend/service/serviceImpl/ProfileServiceImpl.java
  src/main/java/com/example/hanaharmonybackend/web/controller/ProfileController.java
Labels: 🌟 FEAT

#63 [#61] refactor: 글 상세조회 userid 필드추가
  src/main/java/com/example/hanaharmonybackend/service/serviceImpl/BoardServiceImpl.java
  src/main/java/com/example/hanaharmonybackend/web/dto/BoardResponse.java
Labels: 🛠️ REFACTOR

#65 [FEAT] 신고 시 신뢰도에 반영
  src/main/java/com/example/hanaharmonybackend/service/serviceImpl/ChatRoomServiceImpl.java
Labels: 🌟 FEAT

#69 [FEAT] 게시글 상세 조회시 채팅방 연결
  src/main/java/com/example/hanaharmonybackend/payload/code/ErrorStatus.java
  src/main/java/com/example/hanaharmonybackend/repository/ChatRoomRepository.java
  src/main/java/com/example/hanaharmonybackend/service/BoardService.java
  src/main/java/com/example/hanaharmonybackend/service/serviceImpl/BoardServiceImpl.java
  src/main/java/com/example/hanaharmonybackend/service/serviceImpl/ChatRoomServiceImpl.java
  src/main/java/com/example/hanaharmonybackend/web/controller/BoardController.java
  src/main/java/com/example/hanaharmonybackend/web/dto/BoardResponse.java
Labels: 🌟 FEAT, 🛠️ REFACTOR

#72 [FEAT] 본인 글 수정 api 구현
  src/main/java/com/example/hanaharmonybackend/domain/Board.java
  src/main/java/com/example/hanaharmonybackend/service/BoardService.java
  src/main/java/com/example/hanaharmonybackend/service/serviceImpl/BoardServiceImpl.java
  src/main/java/com/example/hanaharmonybackend/service/serviceImpl/PocketCommandServiceImpl.java
  src/main/java/com/example/hanaharmonybackend/web/controller/BoardController.java
Labels: 🌟 FEAT

#75 [FEAT] 채팅방 리스트에서도 금지어 설정
  src/main/java/com/example/hanaharmonybackend/service/serviceImpl/ChatRoomServiceImpl.java
  src/main/java/com/example/hanaharmonybackend/util/BannedWordFilter.java
Labels: 🌟 FEAT
